"""delete columns in_position and direction from instruments table

Revision ID: 29b7bf3683c6
Revises: 9c2cc03165e2
Create Date: 2025-11-02 13:21:39.465847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b7bf3683c6'
down_revision: Union[str, Sequence[str], None] = '9c2cc03165e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'in_position')
    op.drop_column('instruments', 'direction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('direction', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('in_position', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
