"""add_expiration_date_in_instruments_table

Revision ID: 716474b6528c
Revises: 29b7bf3683c6
Create Date: 2026-01-01 21:34:50.696769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716474b6528c'
down_revision: Union[str, Sequence[str], None] = '29b7bf3683c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'expiration_date')
    # ### end Alembic commands ###
